### PR TITLE
Object Detection mAP and Documentation

### PR DESCRIPTION
**Pull request by donovanlavoie**
The preexisting implementation of YOLO object detection in DPP could train on data, automatically patch large images, and perform forward passes. Validation and testing, however, weren't implemented and the console output for testing didn't include it.

This adds testing and validation to the generated Tensorflow graphs for object detection and adds a trio of private functions for use in `compute_full_test_accuracy`(`__yolo_coord_convert` `__yolo_filter_predictions` `__yolo_map`) that implement mAP calculations for the single-class case of object detection. Some documentation was also added in the form of a tutorial page that describes the process of loading data for and training an object detector in comparison to the other tutorial for the leaf counter.

For testing, I acquired a set of annotated plant rosette images from Blanche, converted the annotations into a format that `load_json_labels_from_file` can read, and trained a model on that whole dataset. The testing output, after all of the usual stuff from training, is 

> 04:51PM: Computing total test accuracy/regression loss...
> 04:54PM: Yolo mAP: 0.015191821404839531
> 04:54PM: Shutdown requested, ending session...

The mAP value is pretty garbage on this data, but it is sensible considering that a debug session found that it predicted ~50 / 1500 plants; we don't need to be good yet, we just have to work and do the calculations properly.

### CODE REVIEW

**Comment by jubbens** [comment]
Can we have some sensible defaults for the YOLO parameters in case someone doesn't know what to use? Also, can we make the class label optional if there's only one class in the annotations?

**Comment by jubbens** [comment]
I get errors on running the tests, caused by the relative import of `layers.py` in every test with this line:

```
from . import layers
ImportError: cannot import name layers
```

**Comment by donovanlavoie** [comment]
I'm a bit stumped on why that's happening. I've tried making a new clone in a new venv (installing tensorflow, plantcv, tqdm, and joblib; no DPP install) with a fresh fetch and pull and running the tests. They seem to run fine for me without failing on imports. Any ideas about what might be different about our setups?

**Comment by jubbens** [comment]
It may be an issue with my setup, but in any case it doesn't appear to be an issue specific to this branch so the PR can be merged. I'll keep on investigating the issue in develop.

**Pull request merged**
